[package]
name = "koshelf"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
# CLI
clap = { version = "4.4", features = ["derive"] }
# Error handling
anyhow = "1.0"
thiserror = "1.0"
# Async
tokio = { version = "1.0", features = ["full"] }
# File system
walkdir = "2.4"
# EPUB parsing
zip = "0.6"
# Image processing
image = "0.24"
# Lua parsing
mlua = { version = "0.9", features = ["lua54", "vendored"] }
# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# Templating
askama = { version = "0.12", features = ["serde"] }
# Date/time
chrono = { version = "0.4", features = ["serde"] }
# Logging
log = "0.4"
env_logger = "0.10"
# Path handling
pathdiff = "0.2"
# Base64 encoding for images
base64 = "0.22"
# HTML parsing (for epub content)
scraper = "0.18"
# XML parsing
quick-xml = "0.31"
# HTML sanitization
ammonia = "3.3"
# URL encoding
urlencoding = "2.1" 